/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './picker.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ionic-angular/module';
import * as import5 from './alert.controller';
import * as import6 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import7 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import8 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import9 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import10 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import11 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import12 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import13 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as import14 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import15 from './alert.component.ngfactory';
import * as import16 from 'ionic-angular/components/app/app';
import * as import17 from 'ionic-angular/config/config';
class DatetimePickerModuleInjector extends import0.ɵNgModuleInjector<import1.DatetimePickerModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _IonicModule_4:import4.IonicModule;
  _DatetimePickerModule_5:import1.DatetimePickerModule;
  __NgLocalization_6:import2.NgLocaleLocalization;
  __ɵi_7:import3.ɵi;
  __FormBuilder_8:import3.FormBuilder;
  __DatetimePickerAlertController_9:import5.DatetimePickerAlertController;
  constructor(parent:import0.Injector) {
    super(parent,[
      import6.ActionSheetCmpNgFactory,
      import7.AlertCmpNgFactory,
      import8.IonicAppNgFactory,
      import9.LoadingCmpNgFactory,
      import10.ModalCmpNgFactory,
      import11.PickerCmpNgFactory,
      import12.PopoverCmpNgFactory,
      import13.SelectPopoverNgFactory,
      import14.ToastCmpNgFactory,
      import15.DatetimePickerAlertComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_6():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _ɵi_7():import3.ɵi {
    if ((this.__ɵi_7 == null)) { (this.__ɵi_7 = new import3.ɵi()); }
    return this.__ɵi_7;
  }
  get _FormBuilder_8():import3.FormBuilder {
    if ((this.__FormBuilder_8 == null)) { (this.__FormBuilder_8 = new import3.FormBuilder()); }
    return this.__FormBuilder_8;
  }
  get _DatetimePickerAlertController_9():import5.DatetimePickerAlertController {
    if ((this.__DatetimePickerAlertController_9 == null)) { (this.__DatetimePickerAlertController_9 = new import5.DatetimePickerAlertController(this.parent.get(import16.App),this.parent.get(import17.Config))); }
    return this.__DatetimePickerAlertController_9;
  }
  createInternal():import1.DatetimePickerModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._IonicModule_4 = new import4.IonicModule();
    this._DatetimePickerModule_5 = new import1.DatetimePickerModule();
    return this._DatetimePickerModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import4.IonicModule)) { return this._IonicModule_4; }
    if ((token === import1.DatetimePickerModule)) { return this._DatetimePickerModule_5; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import3.ɵi)) { return this._ɵi_7; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_8; }
    if ((token === import5.DatetimePickerAlertController)) { return this._DatetimePickerAlertController_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DatetimePickerModuleNgFactory:import0.NgModuleFactory<import1.DatetimePickerModule> = new import0.NgModuleFactory<any>(DatetimePickerModuleInjector,import1.DatetimePickerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmVuZy9HaXRIdWIvUGVyc29uYWwvaW9uLWRhdGV0aW1lLXBpY2tlci9zcmMvcGlja2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2JlbmcvR2l0SHViL1BlcnNvbmFsL2lvbi1kYXRldGltZS1waWNrZXIvc3JjL3BpY2tlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
